# Generated by Django 6.0.5 on 2026-05-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='unique_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='unique_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('school', 'unique_user_id')},
        ),
        migrations.CreateModel(
            name='SyncTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=100)),
                ('source_primary_id', models.CharField(max_length=100)),
                ('target_table', models.CharField(max_length=100)),
                ('target_primary_id', models.IntegerField()),
                ('sync_action', models.CharField(max_length=20)),
                ('sync_status', models.CharField(max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
