# Generated by Django 6.0.5 on 2026-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parent_unique_user_id_student_unique_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
