# Generated by Django 6.0.5 on 2026-05-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeacherAssignment',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
