# Generated by Django 6.0.5 on 2026-05-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_subject_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectReportCard',
        ),
    ]
