# Generated by Django 6.0.5 on 2026-05-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_subjectreportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=20)),
                ('source_sub_reportcard_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('report_card_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjectreportcardmaster')),
            ],
            options={
                'db_table': 'subjects_on_report_card',
            },
        ),
    ]
