# Generated by Django 6.0.5 on 2026-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_academicyear_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_present',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='mark',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
