# Generated by Django 6.0.5 on 2026-05-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mark_is_present_mark_percentage_mark_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.examtype'),
        ),
    ]
