# Generated by Django 6.0.5 on 2026-05-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_attendancesession_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='status',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='absent_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='punch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='total_working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
