# Generated by Django 6.0.5 on 2026-05-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='source_exam_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
