# Generated by Django 6.0.5 on 2026-06-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_exam_source_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='source_attendance_session_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentspecialrole',
            name='source_special_role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='source_exam_subject_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='examtype',
            name='source_exam_type_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='source_mark_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
