# Generated by Django 6.0.5 on 2026-06-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_attendancesession_source_attendance_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='departmentspecialrole',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='division',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='homework',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='mark',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='parentfeedback',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='project',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='remedialsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='studentbehavioranalysis',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='studenthealthrecord',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='studentyearsummary',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='subjectreportcard',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='subjectreportcardmaster',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='teacherachievement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='teacheractiveness',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='book',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
    ]
