# Generated by Django 6.0.5 on 2026-06-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_teacherattendance_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='source_student_attendance_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='source_teacher_attendance_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
