# Generated by Django 6.0.5 on 2026-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_studentattendance_source_student_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentyearsummary',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
